### PR TITLE
adds links to the social media sites of congressional legislators #11

### PR DESCRIPTION
**Pull request by bnsmith3**

### CODE REVIEW

**Comment by Superjisan** [comment]
@bnsmith3, can you add a screenshot of your changes. It looks good on my end otherwise.

**Comment by bnsmith3** [comment]
Here's what it looks like:
screenshot

**Comment by Superjisan** [comment]
@bnsmith3, please fix the merge conflicts and I'll give it the old merge.

**Comment by Superjisan** [comment]
Thanks @bnsmith3

**Pull request merged**
